using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Nova.UI.DataService
{
    // Rest of class generated by the Web Service Reference.
    public partial class Category
    {
        public override string ToString()
        {
            return Name;
        }
    }
}
