using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Diagnostics;

namespace Nova.UI.DataService
{
    // Rest of class generated by the Web Service Reference.
    public partial class Customer
    {
        public override string ToString()
        {
            return Name;
        }

        // Method does not fire NotifyPropertyChanged
        public void SetLocationSilent(Location l)
        {
            this._Location = l;
            this._LocationId = l != null ? l.Id : 0;
        }

        // Method does not fire NotifyPropertyChanged
        public void SetCategorySilent(Category ct)
        {
            
            this._Category = ct;
            this._CategoryId = ct != null ? ct.Id : 0;
        }
    }
}
