using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Nova.UI.DataService
{
    // Rest of class generated by the Web Service Reference.
    public partial class CustomerTracking
    {
        /// <summary>
        ///   The friendly description for the operation.
        /// </summary>
        public string OperationDescription
        {
            get
            {
                switch (this.OperationType)
                {
                    case "C":
                        return "Created";
                    case "U":
                        return "Updated";
                    case "D":
                        return "Deleted";
                    default:
                        return "Unchanged";
                }
            }
        }
    }
}
