using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Nova.UI.DataService
{
    // Rest of class generated by the Web Service Reference.
    public partial class Location
    {
        public string Description
        {
            get { return ToString(); }
            set { }
        }
        public override string ToString()
        {
            // Note: No cities in the sample data set
            return string.IsNullOrEmpty(City) 
                ? string.Format("{0}, {1}", this.State, this.Country)
                : string.Format("{0}, {1}, {2}", this.City, this.State, this.Country);

        }
    }
}
